<?php
/** @var Improntus\RetailRocket\Block\Tracker $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php $addToCart = $block->getAddToCart() ?>
<?php $stockId = $block->getStockId() ?>

<?php if($addToCart): ?>

    <?php
    $stockIdHtml = "";

    if($stockId){
        $stockIdHtml = ", {'stockId': '$stockId'}";
    }
    ?>
    <!-- Begin RetailRocket AddToCart Event -->
    <?php
    $scriptString = <<<script
        (window["rrApiOnReady"] = window["rrApiOnReady"] || []).push(function() {
            try { rrApi.addToBasket($addToCart $stockIdHtml) } catch(e) {console.log(e)}
        })
        script;
    ?>

    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    <!-- End RetailRocket AddToCart Event -->
<?php endif ?>
