<?php
/** @var Improntus\RetailRocket\Block\Tracker $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php $customerLogged = $block->getCustomerLogged() ?>

<?php if(is_array($customerLogged) && isset($customerLogged['user_data']['email'])): ?>

    <!-- Begin RetailRocket Customer Email Event -->
    <?php
    $customerEmail = $customerLogged['user_data']['email'];
    $customerAdditional = json_encode($customerLogged['user_data']['additional']);

    $scriptString = <<<script
        (window["rrApiOnReady"] = window["rrApiOnReady"] || []).push(function() {

            var email = "$customerEmail";
            var userAdditional = $customerAdditional;

            try {
                rrApi.setEmail(email, userAdditional);
            } catch(e) {console.log(e)}
        })
        script;
    ?>

    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    <!-- End RetailRocket Customer Email Event -->
<?php endif ?>


