<?php
/** @var Improntus\RetailRocket\Block\Tracker $block */
/** @var Magento\Sales\Model\Order $order */
/** @var Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$order = $block->getOrder();

//Failsafe for bad order id
if (!$order) {
    return;
}
$privacyPoliciesLink = $block->getPrivacyPoliciesUrl();

$email = $escaper->escapeHtml($order->getCustomerEmail());
$customerFirstName = $escaper->escapeHtml($order->getCustomerFirstname());
$customerGenderHtml = '';
$customerAgeHtml = '';
$customerBirthdayHtml = '';

if($order->getCustomerGender()) {
    $customerGender = $escaper->escapeHtml($block->getCustomerGender($order->getCustomerGender()));
    $customerGenderHtml = "userAdditional.gender = '$customerGender'";
}

if($order->getCustomerDob()){
    $customerBirthdayHtml = "userAdditional.birthday = '{$escaper->escapeHtml($block->getCustomerBirthdate($order->getCustomerDob()))}'";
    $customerAgeHtml = "userAdditional.age = '{$escaper->escapeHtml($block->getCustomerAge($order->getCustomerDob()))}'";
}
?>

<?php if($block->getAlwaysSubscribeCustomerEmail()): ?>
    <!-- Begin RetailRocket Email Subscription AlwaysSubscribeCustomerEmail Event -->
    <?php
    $scriptString = <<<script
        var emailSent = false;

        require([
            'jquery'
        ], function ($)
        {
            (window["rrApiOnReady"] = window["rrApiOnReady"] || []).push(function()
            {
                var email = "$email";
                var userAdditional = {};
                userAdditional.name = "$customerFirstName";

                $customerBirthdayHtml
                $customerAgeHtml
                $customerGenderHtml

                try {
                    if(!emailSent)
                    {
                        rrApi.setEmail(email, userAdditional);
                        emailSent = true;
                    }
                } catch(e) {console.log(e)}
            })
        })

    script;
    ?>

    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    <!-- End RetailRocket Email Subscription AlwaysSubscribeCustomerEmail Event -->
<?php else: ?>
    <div class="rr-email-confirmation" style="margin-top: 20px;text-align: left;overflow: hidden;padding: 20px 0">
        <input type="checkbox" id="rr_email" name="rr_email" value="1">
        <label for="rr_email" style="font-weight: bold"><?= $escaper->escapeHtml(__('I would like to receive exclussive offers.'))?></label>
        <p style="font-size: 12px;padding-left: 20px;"><?= /** @noEscape */ __('I have read and accept the <a href="%1">Privacy Policies</a>',$privacyPoliciesLink)?></p>
    </div>

    <!-- Begin RetailRocket Email Subscription Event -->
    <?php
    $scriptString = <<<script
        var emailSent = false;

        require([
            'jquery'
        ], function ($)
        {
            $('#rr_email').click(function ()
            {
                if($(this).is(":checked"))
                {
                    (window["rrApiOnReady"] = window["rrApiOnReady"] || []).push(function()
                    {
                        var email = "$email";
                        var userAdditional = {};

                        userAdditional.name = "$customerFirstName";

                        $customerBirthdayHtml
                        $customerAgeHtml
                        $customerGenderHtml

                        try {
                            if(!emailSent)
                            {
                                rrApi.setEmail(email, userAdditional);
                                emailSent = true;
                            }
                        } catch(e) {console.log(e)}
                    })
                }
            })
        })

    script;
    ?>

    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    <!-- End RetailRocket Email Subscription Event -->
<?php endif; ?>


