<?php
/** @var Improntus\RetailRocket\Block\Tracker $block */
/** @var Magento\Sales\Model\Order $order */
$order = $block->getOrder();

//Failsafe for bad order id
if (!$order) {
    return;
}
$privacyPoliciesLink = $block->getPrivacyPoliciesUrl();
?>

<?php if($block->getAlwaysSubscribeCustomerEmail()): ?>
    <script type="text/javascript">
        var emailSent = false;

        require([
            'jquery'
        ], function ($)
        {
            (window["rrApiOnReady"] = window["rrApiOnReady"] || []).push(function()
            {
                var email = "<?= $order->getCustomerEmail() ?>";
                var userAdditional = {};

                userAdditional.name = "<?= $order->getCustomerFirstname() ?>";

                <?php if($order->getCustomerDob()): ?>
                userAdditional.birthday = "<?= $block->getCustomerBirthdate($order->getCustomerDob()) ?>";
                userAdditional.age = "<?= $block->getCustomerAge($order->getCustomerDob()) ?>";
                <?php endif; ?>

                <?php if($order->getCustomerGender()): ?>
                userAdditional.gender = "<?= $block->getCustomerGender($order->getCustomerGender()) ?>";
                <?php endif; ?>

                try {
                    if(!emailSent)
                    {
                        rrApi.setEmail(email, userAdditional);
                        emailSent = true;
                    }
                } catch(e) {}
            })
        })
    </script>
<?php else: ?>
    <div class="rr-email-confirmation" style="margin-top: 20px;text-align: left;overflow: hidden;padding: 20px 0">
        <input type="checkbox" id="rr_email" name="rr_email" value="1">
        <label for="rr_email" style="font-weight: bold"><?= __('I would like to receive exclussive offers.')?></label>
        <p style="font-size: 12px;padding-left: 20px;"><?= __('I have read and accept the <a href="%1">Privacy Policies</a>',$privacyPoliciesLink)?></p>
    </div>

    <script type="text/javascript">
        var emailSent = false;

        require([
            'jquery'
        ], function ($)
        {
            $('#rr_email').click(function ()
            {
                if($(this).is(":checked"))
                {
                    (window["rrApiOnReady"] = window["rrApiOnReady"] || []).push(function()
                    {
                        var email = "<?= $order->getCustomerEmail() ?>";
                        var userAdditional = {};

                        userAdditional.name = "<?= $order->getCustomerFirstname() ?>";

                        <?php if($order->getCustomerDob()): ?>
                        userAdditional.birthday = "<?= $block->getCustomerBirthdate($order->getCustomerDob()) ?>";
                        userAdditional.age = "<?= $block->getCustomerAge($order->getCustomerDob()) ?>";
                        <?php endif; ?>

                        <?php if($order->getCustomerGender()): ?>
                        userAdditional.gender = "<?= $block->getCustomerGender($order->getCustomerGender()) ?>";
                        <?php endif; ?>

                        try {
                            if(!emailSent)
                            {
                                rrApi.setEmail(email, userAdditional);
                                emailSent = true;
                            }
                        } catch(e) {}
                    })
                }
            })
        })
    </script>
<?php endif; ?>


