<?php
/** @var \Improntus\RetailRocket\Block\Tracker $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<!-- BEGIN RETAIL ROCKET INTEGRATION -->
<?php
$partnerId = $escaper->escapeHtml($block->getPartnerId());

$scriptString = <<<script
    var rrPartnerId = "$partnerId";
    var rrApi = rrApi || {};
    var rrApiOnReady = rrApiOnReady || [];
    (function(d) {
        var ref = d.getElementsByTagName('script')[0];
        var apiJs, apiJsId = 'rrApi-jssdk';
        if (d.getElementById(apiJsId)) return;
        apiJs = d.createElement('script');
        apiJs.id = apiJsId;
        apiJs.async = true;
        apiJs.src = "//cdn.retailrocket.net/content/javascript/tracking.js";
        ref.parentNode.insertBefore(apiJs, ref);
    }(document));
script;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<!-- END RETAIL ROCKET INTEGRATION -->
