<?php

/** @var Magento\Sales\Model\Order $order */
/** @var Improntus\RetailRocket\Block\Tracker $block */
$order = $block->getOrder();

//Failsafe for bad order id
if (!$order) {
	return;
}

$orderItems = [];

foreach ($order->getAllItems() as $item)
{
    if($item->getProductType() == 'configurable')
        continue;

    if($item->getParentItem())
    {
        $itemPrice = $item->getParentItem()->getPriceInclTax();
    }
    else{
        $itemPrice = $item->getPriceInclTax();
    }

    $orderItems[] = [
            'id'  => (int)$item->getProduct()->getId(),
            'qnt' => (int)$item->getQtyOrdered(),
            'price' => (float)$itemPrice
    ];
}

?>

<?php if($order->getStatus() != 'canceled'): ?>
    <!-- Begin RetailRocket Transaction Event -->
    <script type="text/javascript">
        (window["rrApiOnReady"] = window["rrApiOnReady"] || []).push(function() {
            try {
                rrApi.order({
                    "transaction": "<?= /* @noEscape */ $order->getIncrementId()?>",
                    "items": <?= /* @noEscape */ json_encode($orderItems) ?>
            });
            } catch(e) {console.log(e)}
        })
    </script>
    <!-- End RetailRocket Transaction Event -->
<?php endif ?>
