<?php

/** @var Magento\Sales\Model\Order $order */
/** @var Improntus\RetailRocket\Block\Tracker $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$order = $block->getOrder();

//Failsafe for bad order id
if (!$order) {
	return;
}

$orderItems = [];

foreach ($order->getAllItems() as $item)
{
    if($item->getProductType() == 'configurable')
        continue;

    if($item->getParentItem())
    {
        $itemPrice = $item->getParentItem()->getPriceInclTax();
    }
    else{
        $itemPrice = $item->getPriceInclTax();
    }

    $orderItems[] = [
            'id'  => (int)$item->getProduct()->getId(),
            'qnt' => (int)$item->getQtyOrdered(),
            'price' => (float)$itemPrice
    ];
}

?>

<?php if($order->getStatus() != 'canceled'): ?>
    <?php
    $orderIncrementId = $order->getIncrementId();
    $orderItemsJson = json_encode($orderItems);
    ?>

    <!-- Begin RetailRocket Transaction Event -->
    <?php
    $scriptString = <<<script
        (window["rrApiOnReady"] = window["rrApiOnReady"] || []).push(function() {
            try {
                rrApi.order({
                    "transaction": "$orderIncrementId",
                    "items": $orderItemsJson
            });
            } catch(e) {console.log(e)}
        })
        script;
    ?>

    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    <!-- End RetailRocket Transaction Event -->
<?php endif ?>
